apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  namespace: node-app

spec:
  containers:
    - name: node-container
      image: naveenm323/node-app-test-new:latest
      ports:
        - containerPort: 8000
